/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Dao.AgendamentoDAO;
import Entidade.Agenda;
import Entidade.Cliente;
import apoio.Validacao;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    AgendamentoDAO apDAO = new AgendamentoDAO();
    int id = 0;

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCliente() {
        initComponents();
        apDAO.popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText());

        jTextFieldPesquisarCliente.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });

        jTextFieldInserirCliente.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });

        jTextFieldSituacaoCliente.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int c = e.getKeyChar();
                if ((!Character.isDigit(c)) || (jTextFieldSituacaoCliente.getText().length() == 1)) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextUsuarioCliente = new javax.swing.JTextField();
        jFTFEmailCliente = new javax.swing.JFormattedTextField();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jPasswordFieldSenhaCliente = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldInserirCliente = new javax.swing.JTextField();
        jTextFieldSituacaoCliente = new javax.swing.JTextField();
        jButtonCancelarCadastroCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroClientes = new javax.swing.JTable();
        jButtonExcluirCliente = new javax.swing.JButton();
        jButtonEditarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisarCliente = new javax.swing.JTextField();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setTitle("Cadastro Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Salvar Cadastro"));

        jLabelNomeCliente.setText("Nome:");

        jLabel3.setText("E-mail:");

        jLabel7.setText("Senha:");

        jLabel2.setText("Usuario:");

        jTextUsuarioCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextUsuarioClienteKeyTyped(evt);
            }
        });

        jFTFEmailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTFEmailClienteKeyTyped(evt);
            }
        });

        jButtonCadastrarCliente.setText("Cadastrar");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Situação:");

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("*");

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("*");

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("*");

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("*");

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Obs: Campos Com  *  são obrigatórios");

        jLabel12.setText("1 - Ativo         0 - Inativo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabelNomeCliente))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTFEmailCliente)
                                            .addComponent(jTextFieldInserirCliente)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldSituacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextUsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPasswordFieldSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jFTFEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextUsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jPasswordFieldSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldSituacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(jButtonCadastrarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancelarCadastroCliente.setText("Fechar");
        jButtonCancelarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCadastroClienteActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pesquisar"));

        jTableCadastroClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastroClientes);

        jButtonExcluirCliente.setText("Excluir");
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });

        jButtonEditarCliente.setText("Editar");
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        jTextFieldPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarClienteKeyTyped(evt);
            }
        });

        jButtonPesquisarCliente.setText("Pesquisar");
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirCliente)
                    .addComponent(jButtonEditarCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarCadastroCliente)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel1);
        jTabbedPane1.addTab("tab2", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCadastroClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarCadastroClienteActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed

        // criar instancia Agenda
        Agenda cliente = new Agenda();

        // criar instancia AgendamentoDAO
        AgendamentoDAO apDAO = new AgendamentoDAO();

        // inicio dos teste de validação
        if (jTextFieldInserirCliente.getText().length() == 0) { //Verifica se o campo nome está vazio.
            System.out.println("Nome em branco!");
            JOptionPane.showMessageDialog(null, "Nome em branco!");
        } else {
            if (jFTFEmailCliente.getText().length() == 0) { //Verifica se o campo Email está vazio.
                System.out.println("Email em branco !");
                JOptionPane.showMessageDialog(null, "Email em branco!");
            } else {
                if (jTextUsuarioCliente.getText().length() == 0) { //Verifica se o campo Usuario está vazio.
                    System.out.println("Usuário em branco !");
                    JOptionPane.showMessageDialog(null, "Usuário em branco!");
                } else {
                    if (jTextFieldSituacaoCliente.getText().trim().equals("")) { //Verifica se o campo situação está vazio.
                        System.out.println("Situação em branco!");
                        JOptionPane.showMessageDialog(null, "Situação em branco!");
                    } else {
                        if ((jTextFieldSituacaoCliente.getText().equals("1")) || (jTextFieldSituacaoCliente.getText().equals("0"))) {
                            if (jPasswordFieldSenhaCliente.getText().length() == 0) { //Verifica se o campo senha esta vazia.
                                System.out.println("Senha em branco! ");
                                JOptionPane.showMessageDialog(null, "Senha em branco!");
                                if (id != 0) {
                                    if (JOptionPane.showConfirmDialog(this, "Deseja mudar a senha?") == JOptionPane.NO_OPTION) {

                                        // popular o objeto
                                        cliente.setIdCliente(id);
                                        cliente.setNomeCliente(jTextFieldInserirCliente.getText().toString().toUpperCase());
                                        cliente.setEmailCliente(jFTFEmailCliente.getText().toString().toLowerCase());
                                        cliente.setUsuario(jTextUsuarioCliente.getText().toString().toLowerCase());
                                        //cliente.setSenha(jPasswordFieldSenhaCliente.getText());
                                        cliente.setSituacaoCliente(Integer.parseInt(jTextFieldSituacaoCliente.getText()));

                                        // vou mandar cadastrar sem senha
                                        if (apDAO.cadastrarClienteSemSenha(cliente)) {
                                            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
                                            //popula tabela
                                            apDAO.popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText());

                                            // limpa os campos
                                            jTextFieldInserirCliente.setText("");
                                            jFTFEmailCliente.setText("");
                                            jTextUsuarioCliente.setText("");
                                            jPasswordFieldSenhaCliente.setText("");
                                            jTextFieldSituacaoCliente.setText("");

                                            // posiciona cursor
                                            jTextFieldInserirCliente.requestFocus();

                                            // resetar o id
                                            id = 0;
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Problemas ao cadastrar cliente");
                                        }

                                    }
                                }
                            } else { // se estiver tudo ok, manda salvar com senha.

                                // popular o objeto
                                cliente.setIdCliente(id);
                                cliente.setNomeCliente(jTextFieldInserirCliente.getText());
                                cliente.setEmailCliente(jFTFEmailCliente.getText());
                                cliente.setUsuario(jTextUsuarioCliente.getText());
                                cliente.setSenha(jPasswordFieldSenhaCliente.getText());
                                cliente.setSituacaoCliente(Integer.parseInt(jTextFieldSituacaoCliente.getText()));

                                // vou mandar cadastrar com senha
                                if (apDAO.cadastrarCliente(cliente)) {
                                    JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
                                    //popula tabela
                                    apDAO.popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText());

                                    // limpa os campos
                                    jTextFieldInserirCliente.setText("");
                                    jFTFEmailCliente.setText("");
                                    jTextUsuarioCliente.setText("");
                                    jPasswordFieldSenhaCliente.setText("");
                                    jTextFieldSituacaoCliente.setText("");

                                    // posiciona cursor
                                    jTextFieldInserirCliente.requestFocus();

                                    // resetar o id
                                    id = 0;
                                } else {
                                    JOptionPane.showMessageDialog(null, "Problemas ao cadastrar cliente.");
                                }

                            }//fim senha em branco
                            
                        } else{ // mensagem de erro da situação diferente de 1 ou 0
                            JOptionPane.showMessageDialog(null, "Digite apenas '1' ou '0' na situação.");
                        }

                    } //fim situacao em branco

                } //fim usuario em branco

            } //fim email em branco

        } //fim nome em branco


    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed

        String idString = String.valueOf(jTableCadastroClientes.getValueAt(jTableCadastroClientes.getSelectedRow(), 0));

        id = Integer.parseInt(idString);

        // criar instancia AgendamentoDAO
        AgendamentoDAO apDAO = new AgendamentoDAO();

        // criar instancia Agenda
        Agenda cliente = apDAO.consultarCliente(id);

        if (cliente != null) {

            // define os valores do obj nos campos da tela
            jTextFieldInserirCliente.setText(cliente.getNomeCliente());
            jFTFEmailCliente.setText(cliente.getEmailCliente());
            jTextUsuarioCliente.setText(cliente.getUsuario());
            jTextFieldSituacaoCliente.setText(String.valueOf(cliente.getSituacaoCliente()));
            //popula tabela
            apDAO.popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText());

            // mudar de aba
            //jTabbedPane1.setSelectedIndex(0);
            // definir o foco
            jTextFieldInserirCliente.requestFocus();
        }
    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?") == JOptionPane.OK_OPTION) {

            String idString = String.valueOf(jTableCadastroClientes.getValueAt(jTableCadastroClientes.getSelectedRow(), 0));

            int idExclusao = Integer.parseInt(idString);
            
            // criar instancia AgendamentoDAO
            AgendamentoDAO apDAO = new AgendamentoDAO();
            
            // manda excluir
            if (apDAO.excluirCliente(idExclusao)) {
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
                //popula tabela
                apDAO.popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Problemas ao excluir cliente.");
            }
        }
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        new AgendamentoDAO().popularTabelaCliente(jTableCadastroClientes, jTextFieldPesquisarCliente.getText().toString().toUpperCase());
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jTextFieldPesquisarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarClienteKeyTyped
        char c = evt.getKeyChar();  // validar somente letras

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c == '\0'))
            evt.consume();
    }//GEN-LAST:event_jTextFieldPesquisarClienteKeyTyped

    private void jTextUsuarioClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioClienteKeyTyped
        char c = evt.getKeyChar();  // validar somente letras e numeros

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < 0 || c > 9))
            evt.consume();
    }//GEN-LAST:event_jTextUsuarioClienteKeyTyped

    private void jFTFEmailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFEmailClienteKeyTyped
        char c = evt.getKeyChar();  // validar letras e caracteres especiais

        if ((c < 'a' || c > 'z') && (c != '@') && (c != '.'))
            evt.consume();
    }//GEN-LAST:event_jFTFEmailClienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCancelarCadastroCliente;
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JFormattedTextField jFTFEmailCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldSenhaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableCadastroClientes;
    private javax.swing.JTextField jTextFieldInserirCliente;
    private javax.swing.JTextField jTextFieldPesquisarCliente;
    private javax.swing.JTextField jTextFieldSituacaoCliente;
    private javax.swing.JTextField jTextUsuarioCliente;
    // End of variables declaration//GEN-END:variables

}
