/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Dao.AgendamentoDAO;
import Entidade.Agenda;
import apoio.Formatacao;
import apoio.Validacao;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class TelaServico extends javax.swing.JInternalFrame {
    // criar instancia AgendamentoDAO
    AgendamentoDAO apDAO = new AgendamentoDAO();
    
    // criar instancia Formatacao
    Formatacao f = new Formatacao();
    
    int id = 0;

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaServico() {
        initComponents();
        
        // popula tabela
        apDAO.popularTabelaServico(jTableCadastroProdutos, jTextFieldPesquisarServico.getText());
        
        // somente deixa inserir letras
        jTextFieldDescricao.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });
        
        // somente deixa inserir letras
        jTextFieldPesquisarServico.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });
        
        
        // somente deixa inserir numeros
        jFormattedTextFieldValor.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int c = e.getKeyChar();
                if ((!Character.isDigit(c)) ) {
                    Toolkit.getDefaultToolkit().beep();
                    e.consume();
                }
            }
        });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastrarServico = new javax.swing.JButton();
        jTextFieldDescricao = new javax.swing.JTextField();
        jFormattedTextFieldDurcao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jButtonCancelarCadastroServico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroProdutos = new javax.swing.JTable();
        jButtonExcluirServico = new javax.swing.JButton();
        jButtonEditarServico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisarServico = new javax.swing.JTextField();
        jButtonPesquisarServico = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setTitle("Tela Serviços");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastrar Servico"));

        jLabelNomeCliente.setText("Descrição:");

        jLabel3.setText("Valor (R$):");

        jLabel2.setText("Duração:");

        jButtonCadastrarServico.setText("Cadastrar");
        jButtonCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarServicoActionPerformed(evt);
            }
        });

        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyTyped(evt);
            }
        });

        try {
            jFormattedTextFieldDurcao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("*");

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Obs: Campos com ' * ' são obrigatórios");

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeCliente)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDurcao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245))
                            .addComponent(jTextFieldDescricao)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(205, 205, 205)
                        .addComponent(jButtonCadastrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDurcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButtonCadastrarServico))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jButtonCancelarCadastroServico.setText("Fechar");
        jButtonCancelarCadastroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCadastroServicoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pesquisar Serviços"));

        jTableCadastroProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastroProdutos);

        jButtonExcluirServico.setText("Excluir");
        jButtonExcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirServicoActionPerformed(evt);
            }
        });

        jButtonEditarServico.setText("Editar");
        jButtonEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarServicoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        jButtonPesquisarServico.setText("Pesquisar");
        jButtonPesquisarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirServico)
                    .addComponent(jButtonEditarServico))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarCadastroServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarCadastroServico)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Serviços", jPanel1);
        jTabbedPane1.addTab("tab2", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarServicoActionPerformed
        new AgendamentoDAO().popularTabelaServico(jTableCadastroProdutos, jTextFieldPesquisarServico.getText());
    }//GEN-LAST:event_jButtonPesquisarServicoActionPerformed

    private void jButtonEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarServicoActionPerformed
        String idString = String.valueOf(jTableCadastroProdutos.getValueAt(jTableCadastroProdutos.getSelectedRow(), 0));

        id = Integer.parseInt(idString);

        // criar instancia Agenda
        AgendamentoDAO apDAO = new AgendamentoDAO();

        // criar instancia AgendamentoDAO
        Agenda apresentacao = apDAO.consultarServico(id);

        if (apresentacao != null) {
            // define os valores do obj nos campos da tela
            jTextFieldDescricao.setText(apresentacao.getNomeServico());
            jFormattedTextFieldValor.setText(apresentacao.getValorServico());
            jFormattedTextFieldDurcao.setText(apresentacao.getTempoServico());
            //jTextFieldSituacaoServico.setText(String.valueOf(apresentacao.getSituacaoServico()));
            // popula tabela
            apDAO.popularTabelaServico(jTableCadastroProdutos, jTextFieldPesquisarServico.getText());

            // mudar de aba
            //jTabbedPane1.setSelectedIndex(0);
            
            // definir o foco
            jTextFieldDescricao.requestFocus();
        }
    }//GEN-LAST:event_jButtonEditarServicoActionPerformed

    private void jButtonExcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirServicoActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir ?") == JOptionPane.OK_OPTION) {

            String idString = String.valueOf(jTableCadastroProdutos.getValueAt(jTableCadastroProdutos.getSelectedRow(), 0));

            int idExclusao = Integer.parseInt(idString);
            
            // criar instancia Agenda
            AgendamentoDAO apDAO = new AgendamentoDAO();
            
            // manda excluir
            if (apDAO.excluirServico(idExclusao)) {
                JOptionPane.showMessageDialog(null, "Serviço excluído com sucesso!");
                apDAO.popularTabelaServico(jTableCadastroProdutos, jTextFieldPesquisarServico.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Problemas ao excluir serviço.");
            }
        }
    }//GEN-LAST:event_jButtonExcluirServicoActionPerformed


    private void jButtonCancelarCadastroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCadastroServicoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarCadastroServicoActionPerformed


    private void jButtonCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarServicoActionPerformed

        // criar instancia Agenda
        Agenda apresentacao = new Agenda();

        // criar instancia AgendamentoDAO
        AgendamentoDAO apDAO = new AgendamentoDAO();

        // inicio dos teste de validação
        if (jTextFieldDescricao.getText().length() == 0) {  //Verifica se descrição está vazio.
            System.out.println("Descrição em branco!");
            JOptionPane.showMessageDialog(null, "Descrição em branco!");
        } else {
            if (jFormattedTextFieldValor.getText().length() == 0) { //Verifica se valor esta vazio.
                System.out.println("Valor em branco!");
                JOptionPane.showMessageDialog(null, "Valor em branco!");
            } else {
                if (jFormattedTextFieldDurcao.getText().trim().equals(":")) {    //Verifica se duraçao está vazio.
                    System.out.println("Duração em branco!");
                    JOptionPane.showMessageDialog(null, "Duração em branco!");
                } else {
                    // popular o obj
                    apresentacao.setIdServico(id);
                    apresentacao.setNomeServico(jTextFieldDescricao.getText().toString().toUpperCase());
                    apresentacao.setValorServico(jFormattedTextFieldValor.getText());
                    apresentacao.setTempoServico(jFormattedTextFieldDurcao.getText());
                    //apresentacao.setSituacaoServico(Integer.parseInt(jTextFieldSituacaoServico.getText()));

                    // vou mandar cadastrar
                    if (apDAO.cadastrarServico(apresentacao)) {
                        JOptionPane.showMessageDialog(null, "Serviço salvo com sucesso!");
                        //popula tabela
                        apDAO.popularTabelaServico(jTableCadastroProdutos, jTextFieldPesquisarServico.getText());

                        // limpa os campos
                        jTextFieldDescricao.setText("");
                        jFormattedTextFieldValor.setText("");
                        jFormattedTextFieldDurcao.setText("");
                        //jTextFieldSituacaoServico.setText("");

                        // posiciona cursor
                        jTextFieldDescricao.requestFocus();

                        // resetar o id
                        id = 0;
                    } else {
                        JOptionPane.showMessageDialog(null, "Problemas ao cadastrar serviço");
                    }
                    
                } // FIM else duração em branco.
            } // FIM else valor em branco.
        } // FIM else descricao em branco.


    }//GEN-LAST:event_jButtonCadastrarServicoActionPerformed

    private void jTextFieldDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyTyped

    }//GEN-LAST:event_jTextFieldDescricaoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarServico;
    private javax.swing.JButton jButtonCancelarCadastroServico;
    private javax.swing.JButton jButtonEditarServico;
    private javax.swing.JButton jButtonExcluirServico;
    private javax.swing.JButton jButtonPesquisarServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldDurcao;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableCadastroProdutos;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldPesquisarServico;
    // End of variables declaration//GEN-END:variables

}
